### ISSUE TITLE
notifyDataSetChanged() bug

### ISSUE THREAD

**Issue by domgeorg** [Cleveroad/FanLayoutManager#11]
This is related to this [issue](https://issuetracker.google.com/issues/37087322)

When notifyDataSetChanged() on adapter, the RecyclerView scrolls automatically to top. Any thoughts?

**Comment by VadimHalimendikCr** [comment]
Hi, @domgeorg  ,
Thank you for your question and for using our library.
You can fix it this way:
```
    Parcelable recyclerViewState = recyclerView.getLayoutManager().onSaveInstanceState();
    mAdapter.addAll(data);
    mAdapter.notifyDataSetChanged();
    recyclerView.getLayoutManager().onRestoreInstanceState(recyclerViewState);
```
