### ISSUE TITLE
FanLayoutManager::straightenSelectedItem is not reseting isSelectedItemStraightened at the end of animation

### ISSUE THREAD

**Issue by pchmielowski** [Cleveroad/FanLayoutManager#2]
Hello!

As I can see, the member variable `isSelectedItemStraightened` is used to indicate if the selected item is being straightened at the moment. It is set to `true` at the beginning of animation and in my opinion shall be set to false at the end.

**Comment by Iojjj** [comment]
Hi @pchmielowski, 

thanks for your feedback. Our developers will check this.

**Comment by yarovoiag** [comment]
This issue was fixed in new version 1.0.2.
