### ISSUE TITLE
notifyDataSetChange Not working proper

### ISSUE THREAD

**Issue by TechnoStark** [Cleveroad/FanLayoutManager#7]
Hello,

This library working very superb. I found one issue. When i am on detail screen and coming back to fanlayout screen, at that time i need to reload data.

So i am doing normal notifydatasetchange. But that is disturbing fanlayout, and all items and their alignments get disturbed.

Can you tell me any good approach to reload view?

**Comment by yarovoiag** [comment]
Issue was fixed in new version 1.0.4. NotifyDataSetChange will be work properly.
